project_id = "jhkumqyugvezfulkoine"

[functions]
  [functions.admin-reprocess-order]
    verify_jwt = false
  [functions.ai-chat]
    verify_jwt = false
  [functions.api-check]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.cashfree-webhook]
    verify_jwt = false
  [functions.cashfree-checkout]
    verify_jwt = false
  [functions.binance-poll-deposits]
    verify_jwt = false
  [functions.poll-dhru-orders]
    verify_jwt = false
  [functions.binance-webhook]
    verify_jwt = false
  [functions.free-check]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-email]
    verify_jwt = false
  [functions.telegram-notify]
    verify_jwt = false
  [functions.telegram-admin-webhook]
    verify_jwt = false
  [functions.telegram-client-webhook]
    verify_jwt = false
  [functions.telegram-set-webhooks]
    verify_jwt = false
  [functions.telegram-pair]
    verify_jwt = false
  [functions.auth-event]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
