project_id = "jhkumqyugvezfulkoine"

[functions.api-check]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.binance-webhook]
verify_jwt = false

[functions.free-check]
verify_jwt = false

[functions.binance-poll-deposits]
verify_jwt = false

[functions.admin-reprocess-order]
verify_jwt = false

[functions.dhru-feedback]
verify_jwt = false
